BEGIN;

INSERT INTO medidas_preventivas (nombre) VALUES
  ('Mantener niveles adecuados de iluminación'),
  ('Mejorar las condiciones de iluminación de los puestos de trabajo'),
  ('Mantener en buenas condiciones los sistemas de iluminación'),
  ('Controlar el tiempo de exposición'),
  ('Controlar los niveles de exposición'),
  ('Implementar procedimientos de adaptación a condiciones de exposición'),
  ('Vigilar las condiciones del personal expuesto'),
  ('Implementar medidas de aislamiento y protección'),
  ('Controlar y vigilar la exposición del personal'),
  ('Reducir los niveles de ruido desde la fuente'),
  ('Proporcionar protección auditiva adecuada'),
  ('Mantener condiciones adecuadas de recuperación'),
  ('Proporcionar protección adecuada al personal expuesto'),
  ('Reducir las vibraciones generadas por equipos y herramientas'),
  ('Mantener condiciones seguras de operación de equipos y herramientas');

INSERT INTO acciones (nombre) VALUES
  ('Realizar evaluaciones periódicas de los niveles de iluminación'),
  ('Identificar y registrar áreas con iluminación deficiente o excesiva'),
  ('Instalar o mejorar luminarias en áreas con iluminación insuficiente'),
  ('Reubicar luminarias para reducir sombras y deslumbramientos'),
  ('Realizar limpieza periódica de lámparas y luminarias'),
  ('Sustituir lámparas, luminarias o componentes defectuosos'),
  ('Evaluar las condiciones de trabajo antes de iniciar actividades con exposición'),
  ('Establecer tiempos seguros de exposición'),
  ('Establecer períodos graduales de adaptación'),
  ('Programar períodos de descanso y recuperación'),
  ('Realizar evaluación ocupacional del personal expuesto'),
  ('Establecer procedimientos para el reporte de síntomas o malestares'),
  ('Implementar rotación del personal'),
  ('Delimitar y señalizar áreas con riesgo de exposición'),
  ('Verificar el estado de barreras, blindajes y elementos de protección'),
  ('Realizar controles y mediciones periódicas de exposición'),
  ('Mantener actualizado el registro del personal expuesto'),
  ('Inspeccionar equipos, máquinas o instalaciones que produzcan ruido excesivo'),
  ('Realizar mantenimiento preventivo y correctivo de equipos'),
  ('Realizar mediciones periódicas de los niveles de ruido'),
  ('Entregar protección auditiva de acuerdo con las condiciones de exposición'),
  ('Capacitar al personal sobre el uso y conservación de la protección auditiva'),
  ('Habilitar áreas para descanso y recuperación térmica'),
  ('Garantizar disponibilidad de hidratación durante la exposición a temperaturas elevadas'),
  ('Proporcionar equipo o vestimenta de protección adecuada'),
  ('Inspeccionar periódicamente el estado del equipo de protección'),
  ('Inspeccionar equipos y herramientas que produzcan vibraciones excesivas'),
  ('Reparar o sustituir equipos que presenten condiciones inseguras'),
  ('Capacitar al personal sobre el uso seguro de equipos y herramientas');

INSERT INTO recursos (nombre) VALUES
  ('Luxómetro'),
  ('Formato de inspección'),
  ('Registro de hallazgos'),
  ('Luminarias'),
  ('Materiales eléctricos'),
  ('Herramientas'),
  ('Accesorios eléctricos'),
  ('Equipo de limpieza'),
  ('Escalera'),
  ('Repuestos'),
  ('Formato de evaluación de condiciones de trabajo'),
  ('Procedimiento de trabajo seguro'),
  ('Registro de exposición'),
  ('Cronograma de trabajo'),
  ('Área de descanso'),
  ('Formato de evaluación ocupacional'),
  ('Expediente de salud ocupacional'),
  ('Formato de reporte'),
  ('Protocolo de atención'),
  ('Cronograma de rotación'),
  ('Señalización de seguridad'),
  ('Barreras de delimitación'),
  ('Equipo de medición de radiaciones'),
  ('Registro de mediciones'),
  ('Sonómetro'),
  ('Materiales de mantenimiento'),
  ('Tapones auditivos'),
  ('Orejeras de protección auditiva'),
  ('Material de capacitación'),
  ('Mobiliario'),
  ('Agua potable'),
  ('Dispensador de agua'),
  ('Equipo de protección térmica'),
  ('Vestimenta de protección'),
  ('Equipo de medición de vibraciones'),
  ('Manual de operación');

INSERT INTO responsables (nombre) VALUES
  ('Seguridad y Salud Ocupacional'),
  ('Jefe del Servicio'),
  ('Mantenimiento'),
  ('Salud Ocupacional'),
  ('Responsable del Área'),
  ('Almacén'),
  ('Administración');

COMMIT;
